server:
    port: 9630


eureka:
    client:
        allow-redirects: true
        register-with-eureka: true
        enabled: true
        serviceUrl:
            defaultZone: http://3.15.175.14:8000/eureka/

    instance:
        lease-renewal-interval-in-seconds: 5
        ip-address: 13.133.20.25

spring:
    application:
        name: demo01
